// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gilwyxiaalgievmiidzq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdpbHd5eGlhYWxnaWV2bWlpZHpxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1NDIzMDMsImV4cCI6MjA2NDExODMwM30.mBMve1kyycfIYZoSxVrqLJq29gAese17bZLWa_LaboM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);